web/config/routes.rb
require 'resque/server'
require 'resque_scheduler'

Web::Application.routes.draw do
  mount Resque::Server.new, :at => "/resque"

  #devise_for :users

  resources :tits, :only => [:create, :delete, :show] do
    collection do
      get 'pending'
      get 'approved'
      get 'rejected'
      get 'published'
    end

    member do
      put 'approve'
      put 'reject'
    end
  end

end

web/app/models/tits.rb
require 'net/http'
require 'uri'

class Tits
  include Mongoid::Document
  include Mongoid::Symbolize

  field :link, :type => String
  field :published_at, :type => DateTime
  field :added_at, :type => DateTime
  mount_uploader :preview, PreviewUploader
  symbolize :state, :in => [:pending, :published, :approved, :rejected], :default => :pending
  field :fingerprint, :type => String
  field :size

  scope :pending, where(:state => :pending).asc(:added_at)
  scope :published, where(:state => :published).desc(:published_at)
  scope :approved, where(:state => :approved).asc(:added_at)
  scope :rejected, where(:state => :rejected).asc(:added_at)

  def pending?
    state == :pending
  end

  def rejected?
    state == :rejected
  end

  def approved?
    state == :approved
  end

  def published?
    state == :published
  end

  def publish!
    return unless approved?

    Twitter.update(link)
    update_attribute(:state, :published)
  end

def process_image
  uri = URI.parse(self.link)
  http = Net::HTTP.new(uri.host, uri.port)
  http.start() do |http|
    req = Net::HTTP::Get.new(uri.path)
    response = http.request(req)
    tempfile = Tempfile.new(File.basename(uri.path))
    begin
      File.open(tempfile.path, 'wb') { |f| f.write response.body }

      if File.extname(uri.path) =~ /\.png/i
        thumb = Magick::Image.read(tempfile.path).first
        thumb.format = 'JPEG'
        thumb.write tempfile.path
      end

      phasion = Phashion::Image.new(tempfile.path)
      self.fingerprint = '%016x' % phasion.fingerprint
      self.preview = tempfile
      self.preview.store!
      self.size = tempfile.size
    ensure
      tempfile.close
      tempfile.unlink
    end
  end
end

def calc_distances(two_way=true)
  Tits.where(:_id.ne => id).each do |tits|
    distance = Phashion.hamming_distance(fingerprint.hex, tits.fingerprint.hex)
    if distance <= Settings.hamming_threshold
      redis.zadd "distances:#{id}", distance, tits.id
      redis.zadd "distances:#{tits.id}", distance, id if two_way
    end
  end
end


  def similarities(&block)
    s = redis.zrange "distances:#{id}", 0, -1
    s.each do |similarity_id|
      tits = Tits.find(similarity_id)
      yield tits
    end
    nil
  end

  protected

  def redis
    @redis ||= Redis.new
  end

end

web/app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :null => false, :default => ""
  field :encrypted_password, :type => String, :null => false, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Encryptable
  # field :password_salt, :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  has_mobile_fu
end

web/app/controllers/tits_controller.rb
class TitsController < ApplicationController

  def show
    @tits = Tits.find(params[:id])
  end

  def pending
    @tits_list = Tits.pending
    render 'tits'
  end

  def published
    #@tits_list = Tits.published
    #render 'tits'
  end

  def rejected
    @tits_list = Tits.rejected
    render 'tits'
  end

  def approved
    @tits_list = Tits.approved
    render 'tits'
  end

  def create
    Resque.enqueue(NewTits, params[:link])
    render :nothing => true
  end

  def approve
    @tits = Tits.find(params[:id])
    @tits.state = :approved unless @tits.state == :published
    @tits.save!
  end

  def reject
    @tits = Tits.find(params[:id])
    @tits.state = :rejected unless @tits.state == :published
    @tits.save!
  end

  layout 'admin'
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/helpers/tits_helper.rb
module TitsHelper
end

web/app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Web
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    = yield

web/app/views/layouts/admin.mobile.haml
!!!
%html
  %head
    %title Web
    = stylesheet_link_tag "mobile", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    = yield

web/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Web
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    = yield

web/app/views/layouts/application.mobile.haml
!!!
%html
  %head
    %title Web
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    = yield

web/app/views/shared/_header.html.haml
.TitsNav
  = link_to 'Pending', pending_tits_index_path
  |
  = link_to 'Approved', approved_tits_index_path
  |
  = link_to 'Rejected', rejected_tits_index_path

web/app/views/shared/_header.mobile.haml
.TitsNav
  %ul
    %li= link_to 'Pending', pending_tits_index_path
    %li= link_to 'Approved', approved_tits_index_path
    %li= link_to 'Rejected', rejected_tits_index_path

web/app/views/tits/_fotorama_photo.html.haml
= link_to tits.link do
  = image_tag tits.preview.to_s

web/app/views/tits/_fotorama_photo.mobile.haml
= link_to tits.link do
  = image_tag tits.preview.to_s

web/app/views/tits/_fotorama_text.html.haml
.Text{ :id => "text_#{tits.id}" }
  =link_to 'More...', tits_path(tits.id), :target => "_blank"
  %br
  %b Added at
  = tits.added_at.to_s :tits
  %b by
  Stanislav
  %br
  .Actions
    - if tits.pending?
      %b Pending
      = link_to 'Approve', approve_tits_path(tits), :method => :put, :remote => true
      |
      = link_to 'Reject', reject_tits_path(tits), :method => :put, :remote => true
    - elsif tits.approved?
      %b Approved
      = link_to 'Reject', reject_tits_path(tits), :method => :put, :remote => true
    - elsif tits.rejected?
      %b Rejected
      = link_to 'Approve', approve_tits_path(tits), :method => :put, :remote => true

  .Similar
    - tits.similarities do |s|
      = link_to tits_path(s.id), :target => "_blank" do
        = image_tag s.preview.to_s, :size => '60x60', :class => [s.state.to_s.capitalize, "sim_#{s.id}"]

web/app/views/tits/_fotorama_text.mobile.haml
.Text{ :id => "text_#{tits.id}" }
  .Actions
    - if tits.pending?
      = link_to '✓', approve_tits_path(tits), :method => :put, :remote => true
      = link_to '╳', reject_tits_path(tits), :method => :put, :remote => true
    - elsif tits.approved?
      = link_to '╳', reject_tits_path(tits), :method => :put, :remote => true
    - elsif tits.rejected?
      = link_to '✓', approve_tits_path(tits), :method => :put, :remote => true
  .Similar
    - tits.similarities do |s|
      = image_tag s.preview.to_s, :size => '150x150', :class => [s.state.to_s.capitalize, "sim_#{s.id}"]

web/app/views/tits/approve.js.erb
$("#text_<%= @tits.id %> .Actions").html("<b>Approved</b> <%= escape_javascript(link_to 'Reject', reject_tits_path(@tits), :method => :put, :remote => true) %>");

var htmls = $('#fotorama').data('options').html;
var size = $('#fotorama').data('size');
for (var i = 0; i < size; i++) {
  htmls[i].find(".sim_<%= @tits.id %>").removeClass('Pending Approved Rejected Published').addClass('Approved');
}

web/app/views/tits/reject.js.erb
$("#text_<%= @tits.id %> .Actions").html("<b>Rejected</b> <%= escape_javascript(link_to 'Approve', approve_tits_path(@tits), :method => :put, :remote => true) %>");

var htmls = $('#fotorama').data('options').html;
var size = $('#fotorama').data('size');
for (var i = 0; i < size; i++) {
  htmls[i].find(".sim_<%= @tits.id %>").removeClass('Pending Approved Rejected Published').addClass('Rejected');
}

web/app/views/tits/show.html.haml
%b Id:
= @tits.id

%br
%b Source:
= @tits.link

%br
%b Fingerprint:
= @tits.fingerprint

%br
%b State:
- if @tits.pending?
  Pending
- elsif @tits.approved?
  Approved
- elsif @tits.rejected?
  Rejected
- elsif @tits.published?
  Published
  at
  = @tits.published_at.to_s :tits
%br
%b Added at:
= @tits.added_at.to_s :tits

%br
%br
= image_tag @tits.link

%br
- @tits.similarities do |s|
  = link_to tits_path(s.id), :target => "_blank" do
    = image_tag s.preview.to_s, :height => 100, :width => :auto

web/app/views/tits/tits.html.haml
= render '/shared/header'

.TitsGallery
  #fotorama
    - @tits_list.each do |tits|
      = render 'fotorama_photo', :tits => tits

  #fotorama_text{ :style => "display: none;" }
    - @tits_list.each do |tits|
      = render 'fotorama_text', :tits => tits

:javascript
  $(function() {
    var fotorama_text = $('.Text', '#fotorama_text');
    var html = {};
    for (var i = 0; i < fotorama_text.length; i++) {
      html[i] = fotorama_text.eq(i)
    }

    $('#fotorama').fotorama({
      fitToWindowHeight: true,
      width: '100%',
      height: '100%',
      verticalMargin: 60,
      touchStyle: true,
      minPadding: 0,
      thumbBorderColor: '#F0B',
      thumbBorderWidth: 3,
      thumbMargin: 3,
      thumbSize: 60,
      hash: true,
      nav: 'thumb',
      html: html
    });
  });

web/app/views/tits/tits.mobile.haml
= render '/shared/header'

.TitsGallery
  #fotorama
    - @tits_list.each do |tits|
      = render 'fotorama_photo', :tits => tits

  #fotorama_text{ :style => "display: none;" }
    - @tits_list.each do |tits|
      = render 'fotorama_text', :tits => tits

:javascript
  $(function() {
    var fotorama_text = $('.Text', '#fotorama_text');
    var html = {};
    for (var i = 0; i < fotorama_text.length; i++) {
      html[i] = fotorama_text.eq(i)
    }

    $('#fotorama').fotorama({
      fitToWindowHeight: true,
      width: '100%',
      height: '100%',
      verticalMargin: 60,
      touchStyle: true,
      minPadding: 0,
      thumbBorderColor: '#F0B',
      thumbBorderWidth: 3,
      thumbMargin: 3,
      thumbSize: 60,
      hash: true,
      nav: 'none',
      html: html
    });
  });